title: "Tiger Chen"
author: "Tiger Chen"
description: "University Chicago"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: false           # adds a gray frame to the site
show_sidebar: true        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.md", icon: home, title: "Home"}
  - {file: "Projects.html", icon: project-diagram, title: "Industry Experiences"}
  - {title: "CV", icon: file, url: "https://uchicago.box.com/s/z2oxjwqskp7u9vvifw06eeb8z9qops1f"}
  #- {file: "Work.html", title: "Work Experience"}



external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:chenyinlin1998@gmail.com"}
  - {title: Github, icon: github, url: "https://github.com/tigeryy87"}
  - {title: LinkedIn, icon: linkedin, url: "https://www.linkedin.com/in/tigeryy87/"}
  #- {title: Subscribe, icon: rss, url: "/feed.xml"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
